import { Button } from "std-widgets.slint";
import { MemoryTileContainer } from "components/memory-tile-container.slint";
import { MemoryTile,TileData } from "components/memory-tile.slint";

export component MainWindow inherits Window {
    width : 300px;
    height:300px;
    public function set_memoryTiles(memory_tiles: [TileData]) {
        memoryTileContainer.memory_tiles = memory_tiles;
    }

    public function set_disable_tiles(x: bool) {
        memoryTileContainer.disable_tiles = x;
    }

    public function get_memory_tiles() -> [TileData] {
        memoryTileContainer.memory_tiles;
    }

    public function stop_timer() {
        timer.running = false;
    }

    callback check_if_pair_solved();

    VerticalLayout {
        alignment: center;
        padding-bottom: 5px;
        memoryTileContainer := MemoryTileContainer {
            check_if_pair_solved => {
                check_if_pair_solved()
            }
        }

        property <int> total_spend_time: 0;
        timer := Timer {
            interval: 1s;
            running: false;
            triggered => {
                total_spend_time += 1
            }
        }

        Text {
            text: "Total Spend Time: " + total_spend_time + "s";
            x: 5px;
        }

        Button {
            text: "Start";
            width: parent.width - 10px;
            x: 5px;
            clicked => {
                if (timer.running) {
                    timer.running = false;
                } else {
                    timer.running = true;
                }
            }
        }
    }
}
